# Generated by Django 4.1.4 on 2023-01-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Author_Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='Course_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.course'),
        ),
        migrations.AddField(
            model_name='issue_book',
            name='Issued_Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='issue_book',
            name='Valid_Till',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stud_Phno',
            field=models.BigIntegerField(),
        ),
    ]
