# Generated by Django 4.1.4 on 2023-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0002_books_author_name_books_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Stud_Email',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
