# Generated by Django 4.1.4 on 2023-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0003_student_stud_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stud_Email',
            field=models.CharField(max_length=50),
        ),
    ]
